apiVersion: v1
kind: Service
metadata:
  name: hello-lb
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  selector:
    app: django-postgre
  ports:
  - port: 8000
    targetPort: 8000
